on:
  schedule:
    - cron: "55 * * * *" # UTC Time
  workflow_dispatch:

name: Export BugSigDB

jobs:
  export-bugsigdb:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_17

    steps:

      - name: Checkout BugSigDBExports
        uses: actions/checkout@v3
        with:
          path: BugSigDBExports

      - name: Install BugSigDBExports dependencies
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports
          Rscript -e "install.packages(c('rvest', 'readr', 'plyr', 'BiocFileCache'))"

      - name: Install bugsigdbr 
        run: |
          Rscript -e "BiocManager::install('bugsigdbr')"

      - name: Setup git config
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports # Because we need to be in a repository
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Export BugSigDB
        run: |
          echo $(date)
          Rscript $GITHUB_WORKSPACE/BugSigDBExports/inst/scripts/dump_release.R $(date -u '+%Y-%m-%d_%H:%M_UTC') $GITHUB_WORKSPACE/BugSigDBExports
        timeout-minutes: 10

      - name: Commit Exports
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports
          for export in `find . -type f -iname \*.gmt -o -iname \*.csv` 
          do
            export=$(echo $export | sed 's/\.\///g')
            git_diff=$(git diff --numstat $export | sed -e 's/\t//g')
            if [ "$git_diff" = "11$export" -o "$git_diff" = "" ]; then
                echo "No changes to commit for $export"
            else
                echo "Commit changes for $export"
                git add *.gmt *.csv
                git commit -m "Hourly export update"
                git push origin devel
                break
            fi
          done
