on:
  schedule:
    - cron: "55 * * * *" # UTC Time
  workflow_dispatch:

name: Export BugSigDB

jobs:
  export-bugsigdb:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_13

    steps:

      - name: Checkout bugsigdbr
        uses: actions/checkout@v3
        with:
          repository: waldronlab/bugsigdbr
          path: bugsigdbr

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/bugsigdbr
          Rscript -e "devtools::install()"

      - name: Checkout BugSigDBExports
        uses: actions/checkout@v3
        with:
          path: BugSigDBExports

      - name: Install BugSigDBExports dependencies
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports
          Rscript -e "install.packages(c('rvest', 'readr', 'plyr'))"

      - name: Setup git config
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports # Because we need to be in a repository
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Export BugSigDB
        run: |
          echo $(date)
          Rscript $GITHUB_WORKSPACE/BugSigDBExports/inst/scripts/dump_release.R $(date -u '+%Y-%m-%d_%H:%M_UTC') $GITHUB_WORKSPACE/BugSigDBExports
        timeout-minutes: 10

      - name: Commit Exports
        run: |
          cd $GITHUB_WORKSPACE/BugSigDBExports
          gitstring=$(git diff --numstat full_dump.csv | sed -e 's/\t//g')
          nochangestring="11full_dump.csv"
          [[ "$gitstring" == "$nochangestring" ]] && echo "No changes to commit" || (git add . && git commit -m "Hourly export update" && git push origin main)
